site_name: 广联达产品技术文档
nav:
    - 主页: index.md
    - 投屏宝: 
      - '投屏宝规格说明书': '投屏宝/投屏宝规格说明书.md'
      - '投屏宝安装指导手册': '投屏宝/投屏宝安装指导手册.md'
    - 工地宝: 
      - '工地宝用户手册': '工地宝/工地宝用户手册.md'
    - 闸机宝: 
      - '闸机宝用户手册': '闸机宝/闸机宝用户手册.md'
    - 关于: 关于.md
theme: readthedocs
