site_name: 广联达产品技术文档
nav:
    - 主页: index.md
    - 投屏宝: 
      - '投屏宝规格说明书': '投屏宝/投屏宝规格说明书.md'
      - '投屏宝安装指导手册': '投屏宝/投屏宝安装指导手册.md'
    - 工地宝: 
      - '工地宝用户手册': '工地宝/工地宝用户手册.md'
    - 闸机宝: 
      - '闸机宝用户手册': '闸机宝/闸机宝用户手册.md'
    - 速登宝: 
      - '速登宝规格书(肯麦思)': '速登宝/速登宝规格书_肯麦思.md'
    - 人脸识别:
      - '人脸识别规格书(宇泛)': '人脸识别/人脸识别规格书_宇泛.md'
      - '人脸识别安装说明书(弹弓)': '人脸识别/人脸识别安装说明书_弹弓.md'
    - 测温宝:
      - '测温宝用户手册': '测温宝/测温宝用户手册.md'
theme: readthedocs
